import { environment } from 'environments/environment';

export const ENDPOINT = {
    noAuth: {
        getCustomer: environment.apiUrl + '/noauth/get-customer',
    },
    auth: {
        login: environment.apiUrl + '/auth/login',
        logout: environment.apiUrl + '/auth/logout',
        refreshToken: environment.apiUrl + '/auth/refresh-token',
    },
    common: {
        userInfo: environment.apiUrl + '/common/user-info',
        getMenu: environment.apiUrl + '/common/get-menu',
        adminUser: environment.apiUrl + '/common/admin-user',
        allUser: environment.apiUrl + '/common/all-user',
        systemUser: environment.apiUrl + '/common/system-user',
        userGroup: environment.apiUrl + '/common/user-group',
        ldapOption: environment.apiUrl + '/common/ldap-option',
        approverPosition: environment.apiUrl + '/common/approver-position',
        approverGroup: environment.apiUrl + '/common/approver-group',
        meetingType: environment.apiUrl + '/common/meeting-type',
        meetingGroup: environment.apiUrl + '/common/meeting-group',
        allMeetingGroup: environment.apiUrl + '/common/all-meeting-group',
        meetingSubType: environment.apiUrl + '/common/meeting-sub-type',
        agendaObjective: environment.apiUrl + '/common/agenda-objective',
        agendaConfidential: environment.apiUrl + '/common/agenda-confidential',
        agendaApproverFlow: environment.apiUrl + '/common/agenda-approver-flow',
        approverStep: environment.apiUrl + '/common/approver-step',
        documentType: environment.apiUrl + '/common/document-type',
        lineApproved: environment.apiUrl + '/common/line-approve',
    },
    meeting: {
        search: environment.apiUrl + '/meeting/search',
        duplicate: environment.apiUrl + '/meeting/duplicate',
        getAll: environment.apiUrl + '/meeting/get-all',
        get: environment.apiUrl + '/meeting/get',
        update: environment.apiUrl + '/meeting/update',
        add: environment.apiUrl + '/meeting/add',
        delete: environment.apiUrl + '/meeting/delete',
        agundumExport: environment.apiUrl + '/meeting/agendum-export',
    },
    meetingAgenda: {
        search: environment.apiUrl + '/meeting-agenda/search',
        get: environment.apiUrl + '/meeting-agenda/get',
        update: environment.apiUrl + '/meeting-agenda/update',
        add: environment.apiUrl + '/meeting-agenda/add',
        delete: environment.apiUrl + '/meeting-agenda/delete',
        moveDown: environment.apiUrl + '/meeting-agenda/move-down',
        moveUp: environment.apiUrl + '/meeting-agenda/move-up',
        move: environment.apiUrl + '/meeting-agenda/move',
        refAttachmentGet:
            environment.apiUrl + '/meeting-agenda/ref-attachment-get',
        agendaReserveGet:
            environment.apiUrl + '/meeting-agenda/agenda-reserve-get',
        agendaReserveWatingGet:
            environment.apiUrl + '/meeting-agenda/agenda-reserve-wating-get',
        agendaReserveDetailGet:
            environment.apiUrl + '/meeting-agenda/agenda-reserve-detail-get',
        reserveImport: environment.apiUrl + '/meeting-agenda/reserve-import',
        agendaMeetingReserveGet:
            environment.apiUrl + '/meeting-agenda/agenda-meeting-reserve-get',
        attachmentReplace:
            environment.apiUrl + '/meeting-agenda/attachment-replace',
        attachmentAdd: environment.apiUrl + '/meeting-agenda/attachment-add',
        attachmentDelete:
            environment.apiUrl + '/meeting-agenda/attachment-delete',
        attachmentPos: environment.apiUrl + '/meeting-agenda/attachment-pos',
        attachmentPosBatch:
            environment.apiUrl + '/meeting-agenda/attachment-pos-batch',
        attachmentPermission:
            environment.apiUrl + '/meeting-agenda/attachment-permission',
        attachmentPermissionForList:
            environment.apiUrl +
            '/meeting-agenda/attachment-permission-for-list',
        presenterAttachmentAdd:
            environment.apiUrl + '/meeting-agenda/presenter-attachment-add',
        presenterAttachmentDelete:
            environment.apiUrl + '/meeting-agenda/presenter-attachment-delete',
        getVote: environment.apiUrl + '/meeting-agenda/get-vote',
    },
    userGroup: {
        search: environment.apiUrl + '/userGroup/search',
        getAll: environment.apiUrl + '/userGroup/get-all',
        get: environment.apiUrl + '/userGroup/get',
        update: environment.apiUrl + '/userGroup/update',
        add: environment.apiUrl + '/userGroup/add',
        delete: environment.apiUrl + '/userGroup/delete',
    },
    meetingRoom: {
        search: environment.apiUrl + '/MeetingRoom/search',
        getAll: environment.apiUrl + '/MeetingRoom/get-all',
        get: environment.apiUrl + '/MeetingRoom/get',
        update: environment.apiUrl + '/MeetingRoom/update',
        add: environment.apiUrl + '/MeetingRoom/add',
        delete: environment.apiUrl + '/MeetingRoom/delete',
    },

    user: {
        search: environment.apiUrl + '/user/search',
        getAll: environment.apiUrl + '/user/get-all',
        get: environment.apiUrl + '/user/get',
        update: environment.apiUrl + '/user/update',
        add: environment.apiUrl + '/user/add',
        delete: environment.apiUrl + '/user/delete',
    },
    memberGroup: {
        search: environment.apiUrl + '/member-group/search',
        getAll: environment.apiUrl + '/member-group/get-all',
        get: environment.apiUrl + '/member-group/get',
        update: environment.apiUrl + '/member-group/update',
        add: environment.apiUrl + '/member-group/add',
        delete: environment.apiUrl + '/member-group/delete',
    },
    meetingGroup: {
        search: environment.apiUrl + '/meeting-group/search',
        getAll: environment.apiUrl + '/meeting-group/get-all',
        get: environment.apiUrl + '/meeting-group/get',
        update: environment.apiUrl + '/meeting-group/update',
        add: environment.apiUrl + '/meeting-group/add',
        delete: environment.apiUrl + '/meeting-group/delete',
    },
    meetingType: {
        search: environment.apiUrl + '/MeetingType/search',
        getAll: environment.apiUrl + '/MeetingType/get-all',
        get: environment.apiUrl + '/MeetingType/get',
        update: environment.apiUrl + '/MeetingType/update',
        add: environment.apiUrl + '/MeetingType/add',
        delete: environment.apiUrl + '/MeetingType/delete',
    },
    meetingSubType: {
        search: environment.apiUrl + '/MeetingSubType/search',
        getAll: environment.apiUrl + '/MeetingSubType/get-all',
        get: environment.apiUrl + '/MeetingSubType/get',
        update: environment.apiUrl + '/MeetingSubType/update',
        add: environment.apiUrl + '/MeetingSubType/add',
        delete: environment.apiUrl + '/MeetingSubType/delete',
    },
    documentTemplate: {
        search: environment.apiUrl + '/documentTemplate/search',
        getAll: environment.apiUrl + '/documentTemplate/get-all',
        get: environment.apiUrl + '/documentTemplate/get',
        update: environment.apiUrl + '/documentTemplate/update',
        add: environment.apiUrl + '/documentTemplate/add',
        delete: environment.apiUrl + '/documentTemplate/delete',
    },
    documentType: {
        search: environment.apiUrl + '/DocumentType/search',
        getAll: environment.apiUrl + '/DocumentType/get-all',
        get: environment.apiUrl + '/DocumentType/get',
        update: environment.apiUrl + '/DocumentType/update',
        add: environment.apiUrl + '/DocumentType/add',
        delete: environment.apiUrl + '/DocumentType/delete',
    },
    agendaApprove: {
        myApprove: environment.apiUrl + '/AgendaApprove/my-approve',
        myHistory: environment.apiUrl + '/AgendaApprove/my-history',
        get: environment.apiUrl + '/AgendaApprove/get',
        approve: environment.apiUrl + '/AgendaApprove/approve',
        approveCancel: environment.apiUrl + '/AgendaApprove/approve-cancel',
        approveEdit: environment.apiUrl + '/AgendaApprove/approve-edit',
    },
    agendaRequestItem: {
        search: environment.apiUrl + '/AgendaRequestItem/search',
    },
    agendaRequest: {
        getAvailableMeeting:
            environment.apiUrl + '/AgendaRequest/get-available-meeting',
        submit: environment.apiUrl + '/AgendaRequest/submit',
        docSubmit: environment.apiUrl + '/AgendaRequest/doc-submit',
        reSubmit: environment.apiUrl + '/AgendaRequest/re-submit',
        requestCancel: environment.apiUrl + '/AgendaRequest/request-cancel',
        requestEdit: environment.apiUrl + '/AgendaRequest/request-edit',
        search: environment.apiUrl + '/AgendaRequest/search',
        get: environment.apiUrl + '/AgendaRequest/get',
        update: environment.apiUrl + '/AgendaRequest/update',
        add: environment.apiUrl + '/AgendaRequest/add',
        delete: environment.apiUrl + '/AgendaRequest/delete',
        addTeam: environment.apiUrl + '/AgendaRequest/add-team',
        removeTeam: environment.apiUrl + '/AgendaRequest/remove-team',
        addAttachment: environment.apiUrl + '/AgendaRequest/add-attachment',
        removeAttachment:
            environment.apiUrl + '/AgendaRequest/remove-attachment',
        posAttachment: environment.apiUrl + '/AgendaRequest/pos-attachment',
        posAttachmentBatch:
            environment.apiUrl + '/AgendaRequest/pos-attachment-batch',
        getByMeeting: environment.apiUrl + '/AgendaRequest/get-by-meeting',
        export: environment.apiUrl + '/AgendaRequest/export',
        updateAttachmentPermission:
            environment.apiUrl + '/AgendaRequest/update-attachment-permission',
        updateAttachmentPermissionForList:
            environment.apiUrl +
            '/AgendaRequest/update-attachment-permission-for-list',
        getMeetingRelation:
            environment.apiUrl + '/AgendaRequest/get-meeting-relation',
    },

    agendaReview: {
        search: environment.apiUrl + '/agenda-review/search',
        getAll: environment.apiUrl + '/agenda-review/get-all',
        get: environment.apiUrl + '/agenda-review/get',
        update: environment.apiUrl + '/agenda-review/update',
        add: environment.apiUrl + '/agenda-review/add',
        delete: environment.apiUrl + '/agenda-review/delete',
    },
    approverGroup: {
        search: environment.apiUrl + '/ApproverGroup/search',
        getAll: environment.apiUrl + '/ApproverGroup/get-all',
        get: environment.apiUrl + '/ApproverGroup/get',
        update: environment.apiUrl + '/ApproverGroup/update',
        add: environment.apiUrl + '/ApproverGroup/add',
        delete: environment.apiUrl + '/ApproverGroup/delete',
    },
    documentApprove: {
        search: environment.apiUrl + '/document-approve/search',
        getAll: environment.apiUrl + '/document-approve/get-all',
        get: environment.apiUrl + '/document-approve/get',
        update: environment.apiUrl + '/document-approve/update',
        add: environment.apiUrl + '/document-approve/add',
        delete: environment.apiUrl + '/document-approve/delete',
    },
    meetingMgm: {
        search: environment.apiUrl + '/meeting-mgm/search',
        getAll: environment.apiUrl + '/meeting-mgm/get-all',
        get: environment.apiUrl + '/meeting-mgm/get',
        update: environment.apiUrl + '/meeting-mgm/update',
        add: environment.apiUrl + '/meeting-mgm/add',
        delete: environment.apiUrl + '/meeting-mgm/delete',
    },
    invitation: {
        search: environment.apiUrl + '/invitation/search',
        getAll: environment.apiUrl + '/invitation/get-all',
        get: environment.apiUrl + '/invitation/get',
        update: environment.apiUrl + '/invitation/update',
        add: environment.apiUrl + '/invitation/add',
        delete: environment.apiUrl + '/invitation/delete',
    },
    minuteConfirm: {
        search: environment.apiUrl + '/minute-confirm/search',
        getAll: environment.apiUrl + '/minute-confirm/get-all',
        get: environment.apiUrl + '/minute-confirm/get',
        update: environment.apiUrl + '/minute-confirm/update',
        add: environment.apiUrl + '/minute-confirm/add',
        delete: environment.apiUrl + '/minute-confirm/delete',
    },
    joinResult: {
        search: environment.apiUrl + '/join-result/search',
        getAll: environment.apiUrl + '/join-result/get-all',
        get: environment.apiUrl + '/join-result/get',
        update: environment.apiUrl + '/join-result/update',
        add: environment.apiUrl + '/join-result/add',
        delete: environment.apiUrl + '/join-result/delete',
    },
    fileOpen: {
        search: environment.apiUrl + '/file-open/search',
        getAll: environment.apiUrl + '/file-open/get-all',
        get: environment.apiUrl + '/file-open/get',
        update: environment.apiUrl + '/file-open/update',
        add: environment.apiUrl + '/file-open/add',
        delete: environment.apiUrl + '/file-open/delete',
    },
    meetingAttendee: {
        search: environment.apiUrl + '/MeetingAttendee/search',
        getAll: environment.apiUrl + '/MeetingAttendee/get-all',
        getuserGroup: environment.apiUrl + '/MeetingAttendee/get-user-group',
        get: environment.apiUrl + '/MeetingAttendee/get',
        update: environment.apiUrl + '/MeetingAttendee/update',
        add: environment.apiUrl + '/MeetingAttendee/add',
        delete: environment.apiUrl + '/MeetingAttendee/delete',
        setChirman: environment.apiUrl + '/MeetingAttendee/set-chirman',
        removeChirman: environment.apiUrl + '/MeetingAttendee/remove-chirman',
        setSecretary: environment.apiUrl + '/MeetingAttendee/set-secretary',
        removeSecretary:
            environment.apiUrl + '/MeetingAttendee/remove-secretary',
    },
    vote: {
        search: environment.apiUrl + '/vote/search',
        getAll: environment.apiUrl + '/vote/get-all',
        get: environment.apiUrl + '/vote/get',
        update: environment.apiUrl + '/vote/update',
        add: environment.apiUrl + '/vote/add',
        delete: environment.apiUrl + '/vote/delete',
    },
    join: {
        search: environment.apiUrl + '/join/search',
        getAll: environment.apiUrl + '/join/get-all',
        get: environment.apiUrl + '/join/get',
        update: environment.apiUrl + '/join/update',
        add: environment.apiUrl + '/join/add',
        delete: environment.apiUrl + '/join/delete',
    },
    follow: {
        search: environment.apiUrl + '/follow/search',
        getAll: environment.apiUrl + '/follow/get-all',
        get: environment.apiUrl + '/follow/get',
        update: environment.apiUrl + '/follow/update',
        add: environment.apiUrl + '/follow/add',
        delete: environment.apiUrl + '/follow/delete',
    },
    followUp: {
        search: environment.apiUrl + '/FollowUp/search',
        getAll: environment.apiUrl + '/FollowUp/get-all',
        get: environment.apiUrl + '/FollowUp/get',
        update: environment.apiUrl + '/FollowUp/update',
        add: environment.apiUrl + '/FollowUp/add',
        delete: environment.apiUrl + '/FollowUp/delete',
    },
    myAgendaReserve: {
        search: environment.apiUrl + '/my-agenda-reserve/search',
        getAll: environment.apiUrl + '/my-agenda-reserve/get-all',
        get: environment.apiUrl + '/my-agenda-reserve/get',
        update: environment.apiUrl + '/my-agenda-reserve/update',
        add: environment.apiUrl + '/my-agenda-reserve/add',
        delete: environment.apiUrl + '/my-agenda-reserve/delete',
    },
    service: {
        uploadFile: environment.apiUrl + '/service/upload',
        updateFileDesc: environment.apiUrl + '/service/update-file-desc',
        ldapSearch: environment.apiUrl + '/service/ldap-search',
        getAntiforgery: environment.apiUrl + '/service/get-antiforgery',
    },
    industrialGroup: {
        search: environment.apiUrl + '/industrial-group/search',
        getAll: environment.apiUrl + '/industrial-group/get-all',
        get: environment.apiUrl + '/industrial-group/get',
        update: environment.apiUrl + '/industrial-group/update',
        add: environment.apiUrl + '/industrial-group/add',
        delete: environment.apiUrl + '/industrial-group/delete',
    },
    activeDirectory: {
        search: environment.apiUrl + '/active-directory/search',
        getAll: environment.apiUrl + '/active-directory/get-all',
        get: environment.apiUrl + '/active-directory/get',
        update: environment.apiUrl + '/active-directory/update',
        add: environment.apiUrl + '/active-directory/add',
        delete: environment.apiUrl + '/active-directory/delete',
    },
    member: {
        search: environment.apiUrl + '/member/search',
        getAll: environment.apiUrl + '/member/get-all',
        get: environment.apiUrl + '/member/get',
        update: environment.apiUrl + '/member/update',
        add: environment.apiUrl + '/member/add',
        delete: environment.apiUrl + '/member/delete',
    },
    employee: {
        search: environment.apiUrl + '/employee/search',
        getAll: environment.apiUrl + '/employee/get-all',
        get: environment.apiUrl + '/employee/get',
        update: environment.apiUrl + '/employee/update',
        add: environment.apiUrl + '/employee/add',
        delete: environment.apiUrl + '/employee/delete',
    },
    customerType: {
        search: environment.apiUrl + '/customer-type/search',
        getAll: environment.apiUrl + '/customer-type/get-all',
        get: environment.apiUrl + '/customer-type/get',
        update: environment.apiUrl + '/customer-type/update',
        add: environment.apiUrl + '/customer-type/add',
        delete: environment.apiUrl + '/customer-type/delete',
    },
    customer: {
        search: environment.apiUrl + '/customer/search',
        getAll: environment.apiUrl + '/customer/get-all',
        get: environment.apiUrl + '/customer/get',
        update: environment.apiUrl + '/customer/update',
        add: environment.apiUrl + '/customer/add',
        delete: environment.apiUrl + '/customer/delete',
    },
    agendaApprover: {
        search: environment.apiUrl + '/AgendaApproverFlow/search',
        getAll: environment.apiUrl + '/AgendaApproverFlow/get-all',
        get: environment.apiUrl + '/AgendaApproverFlow/get',
        update: environment.apiUrl + '/AgendaApproverFlow/update',
        add: environment.apiUrl + '/AgendaApproverFlow/add',
        delete: environment.apiUrl + '/AgendaApproverFlow/delete',
    },
    agendaConfidential: {
        search: environment.apiUrl + '/AgendaConfidential/search',
        getAll: environment.apiUrl + '/AgendaConfidential/get-all',
        get: environment.apiUrl + '/AgendaConfidential/get',
        update: environment.apiUrl + '/AgendaConfidential/update',
        add: environment.apiUrl + '/AgendaConfidential/add',
        delete: environment.apiUrl + '/AgendaConfidential/delete',
    },
    approverStep: {
        search: environment.apiUrl + '/ApproverStep/search',
        getAll: environment.apiUrl + '/ApproverStep/get-all',
        get: environment.apiUrl + '/ApproverStep/get',
        update: environment.apiUrl + '/ApproverStep/update',
        add: environment.apiUrl + '/ApproverStep/add',
        delete: environment.apiUrl + '/ApproverStep/delete',
    },
    agendaObjective: {
        search: environment.apiUrl + '/AgendaObjective/search',
        getAll: environment.apiUrl + '/AgendaObjective/get-all',
        get: environment.apiUrl + '/AgendaObjective/get',
        update: environment.apiUrl + '/AgendaObjective/update',
        add: environment.apiUrl + '/AgendaObjective/add',
        delete: environment.apiUrl + '/AgendaObjective/delete',
    },
    approverPosition: {
        search: environment.apiUrl + '/ApproverPosition/search',
        getAll: environment.apiUrl + '/ApproverPosition/get-all',
        get: environment.apiUrl + '/ApproverPosition/get',
        update: environment.apiUrl + '/ApproverPosition/update',
        add: environment.apiUrl + '/ApproverPosition/add',
        delete: environment.apiUrl + '/ApproverPosition/delete',
    },
    approverConfig: {
        search: environment.apiUrl + '/ApproverConfig/search',
        getAll: environment.apiUrl + '/ApproverConfig/get-all',
        get: environment.apiUrl + '/ApproverConfig/get',
        update: environment.apiUrl + '/ApproverConfig/update',
        add: environment.apiUrl + '/ApproverConfig/add',
        delete: environment.apiUrl + '/ApproverConfig/delete',
    },
    downloadLog: {
        search: environment.apiUrl + '/DownloadLog/search',
    },

    venue: {
        search: environment.apiUrl + '/venue/search',
        getAll: environment.apiUrl + '/venue/get-all',
        get: environment.apiUrl + '/venue/get',
        update: environment.apiUrl + '/venue/update',
        add: environment.apiUrl + '/venue/add',
        delete: environment.apiUrl + '/venue/delete',
    },

    minute: {
        add: environment.apiUrl + '/minute/add',
        sendConfirm: environment.apiUrl + '/minute/send-confirm',
        getHistory: environment.apiUrl + '/minute/get-history',
        getConfirm: environment.apiUrl + '/minute/get-confirm',
    },

    minuteRequest: {
        submit: environment.apiUrl + '/MinuteRequest/submit',
        get: environment.apiUrl + '/MinuteRequest/get',
    },

    minuteApprove: {
        myApprove: environment.apiUrl + '/MinuteApprove/my-approve',
        myHistory: environment.apiUrl + '/MinuteApprove/my-history',
        get: environment.apiUrl + '/MinuteApprove/get',
        approve: environment.apiUrl + '/MinuteApprove/approve',
    },
    package: {
        info: environment.apiUrl + '/Package/info',
    },
    log: {
        login: environment.apiUrl + '/log/login',
        loginFail: environment.apiUrl + '/log/login-fail',
        error: environment.apiUrl + '/log/error',
        mail: environment.apiUrl + '/log/mail',
    },
};
